%% THIS ROUTINE WAS CREATED FOR THE ESTIMATION OF THE PARTITION FNCTIONS

% IT WAS CONCEIVED FOR BEING USED WITH THE CHHABRA-JENSEN METHOD ALGORITHM,
% ORIGINALLY

% THE FUNCTION RECEIVES 5 INPUT VARIABLES, THE 'x' AND 'y' VARIABLES OF A TIME
% SERIES, THE INITIAL POINT OF THE WINDOW 'EI' AND THE FINAL 'Ef' AND TOTAL
% NUMBER OF POINTS IN THE TIME SERIES.

function [mysum] = calcSumM(x, y, Ei, Ef)

mysum = sum(y(x>Ei & x<=Ef));
% THE VARIAVLE 'mysum' WILL RETURN THE SUM OF ALL ELEMENTS IN A GIVEN WINDOW
% mysum=0;
% 
% %% lOOP OVER ALL THE ELEMENTS OF THE TIME SERIES (x,y)
% for i=1:N
%     
%     %% IS THIS VALUE INSIDE OF THE DESIRED WINDOW (PARTITION)?
%     if(x(i)>Ei && x(i)<=Ef)
%         
%         %IN A POSITIVE CASE THE VALUE WILL BE ADDED TO THE VARIABLE 'mysum',
%         %WHICH WILL BE REPORTED WHEN THE ROUTINE FINISHES RUNNING
%         mysum = mysum + y(i);
%         
%     end
% end
end