version: "3"
services:

  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    volumes:
          - "./src:/src" 
          - "./data:/data"
          - "./jupyter:/jupyter"
